#!/bin/sh
#
# graylog2-server:   graylog2 message collector
#
# chkconfig: - 98 02
# description:  This daemon listens for syslog and GELF messages and stores them in mongodb
#
CMD=$1

start() {
    echo "Starting graylog2-server ..."
    nohup java -Duser.timezone=GMT -jar /graylog2/graylog2-server-0.9.6/graylog2-server.jar > /var/log/graylog2.log 2>&1 &
}

stop() {
    PID=`cat /tmp/graylog2.pid`
    echo "Stopping graylog2-server ($PID) ..."
    kill $PID
}

restart() {
    echo "Restarting graylog2-server ..."
    stop
    start
}

case "$CMD" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage $0 {start|stop|restart}"
        RETVAL=1
esac
